version: '3.9'
# detalhes em https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  web:
    build:
      context: _docker
      dockerfile: php.Dockerfile
    ports:
      - "8008:80"
    volumes:
      - .:/var/www/html/
    environment:
      AMBIENTE: docker
      CI_ENVIRONMENT: development
              
  postgres:
    build:
      context: _docker
      dockerfile: postgres.Dockerfile
    ports:
      - "9008:5432"
    volumes:
      - ./_db/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: adm_ci4base
      POSTGRES_PASSWORD: adm_ci4base
      POSTGRES_DB: db_ci4base
   
  adminer:    
    image: michalhosna/adminer
    ports:
      - "6008:8080"
    environment:            
      ADMINER_DRIVER: pgsql
      ADMINER_SERVER: postgres
      ADMINER_DB: db_ci4base
      ADMINER_PASSWORD: adm_ci4base
      ADMINER_USERNAME: adm_ci4base
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: CI4-Base

networks:
  default:
    name: ci4base_network
